#!/bin/bash

# ==============================================================================
# Nextflow Pipeline Monitor
# ==============================================================================
#
# Description:
#   This script monitors the progress and status of a Nextflow pipeline in real-time.
#   It parses the Nextflow trace file and log file to provide a comprehensive dashboard
#   including:
#     - Overall pipeline progress bar.
#     - Detailed status of each process (Running, Pending, Completed, Failed).
#     - Resource usage statistics for recently completed tasks.
#     - Alerts on retried tasks and recent failures.
#
# Usage:
#   ./monitor_status.rev.sh [options]
#
#   # Real-time monitoring example:
#   watch -n 5 --color ./monitor_status.rev.sh
#
# Options:
#   -l, --log, --show-log   Display the latest log messages at the end of the report.
#
# Dependencies:
#   - Requires access to 'trace.txt' and 'nextflow_head.log' generated by the pipeline.
#   - Uses 'squeue' to check Slurm job status.
# Author: 
#   ZHAO TIE   
#
# ==============================================================================

TRACE_FILE="trace.txt"
LOG_FILE="nextflow_head.log"
SHOW_LOG=false

# Parse arguments
for arg in "$@"; do
    case $arg in
        -l|--log|--show-log)
            SHOW_LOG=true
            ;;
    esac
done

# Colors
BOLD='\033[1m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# clear
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  NEXTFLOW PIPELINE MONITOR${NC}                                          ${CYAN}$(date '+%Y-%m-%d %H:%M:%S')${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

if [ ! -f "$TRACE_FILE" ]; then
    echo -e "${YELLOW}Waiting for trace file ($TRACE_FILE) to be generated...${NC}"
    if [ -f "$LOG_FILE" ]; then
        echo "Tail of log file:"
        tail -n 3 "$LOG_FILE"
    fi
    exit 0
fi

# Capture Slurm State ONCE for consistency
# Filter by Current Working Directory to avoid picking up jobs from other runs
SLURM_RAW=$(mktemp)
PWD_REAL=$(realpath .)
squeue -u $(whoami) -h -o "%t %.100j %.100Z" | grep "$PWD_REAL" > "$SLURM_RAW"

# 1. Overall Stats
# Calculate Real Total from Log (Sum of max tasks per process)
TOTAL_EXPECTED=0
if [ -f "$LOG_FILE" ]; then
    TOTAL_EXPECTED=$(grep "process >" "$LOG_FILE" | grep " of " | sed -E 's/.*process > ([^ ]+).+of ([0-9]+).*/\1 \2/' | awk '{if($2 > max[$1]) max[$1]=$2} END {for(k in max) sum+=max[k]; print sum}')
fi

# Fallback to trace count if log parsing fails or trace has more
# Use unique task names to avoid counting retries/attempts as separate tasks
TRACE_COUNT=0
if [ -f "$TRACE_FILE" ]; then
    TRACE_COUNT=$(tail -n +2 "$TRACE_FILE" | cut -f4 | sort -u | wc -l)
fi

if [ -z "$TOTAL_EXPECTED" ] || [ "$TOTAL_EXPECTED" -eq 0 ]; then
    TOTAL_EXPECTED=$TRACE_COUNT
elif [ "$TRACE_COUNT" -gt "$TOTAL_EXPECTED" ]; then
    # Only update if unique trace count is higher (discovered more logical tasks)
    TOTAL_EXPECTED=$TRACE_COUNT
fi

COMPLETED=$(grep -c "COMPLETED" "$TRACE_FILE")
CACHED=$(grep -c "CACHED" "$TRACE_FILE")
FAILED=$(grep -c "FAILED" "$TRACE_FILE")
SUCCESS_COUNT=$((COMPLETED + CACHED))

# Get Running/Pending count from Slurm (using captured state)
SLURM_RUNNING=$(grep " nf-" "$SLURM_RAW" | grep -E "^ *R|^ *CG" | wc -l)
SLURM_PENDING=$(grep " nf-" "$SLURM_RAW" | grep "^ *PD" | wc -l)

# Progress Calculation (Safe Division)
PERCENT="0.0"
FILLED=0
BAR_WIDTH=50

if [ "$TOTAL_EXPECTED" -gt 0 ]; then
    PERCENT=$(awk -v num="$SUCCESS_COUNT" -v den="$TOTAL_EXPECTED" 'BEGIN {printf "%.1f", (num / den) * 100}')
    FILLED=$(awk -v num="$SUCCESS_COUNT" -v den="$TOTAL_EXPECTED" -v width="$BAR_WIDTH" 'BEGIN {printf "%.0f", (num / den) * width}')
fi

# Ensure FILLED is a valid integer
if ! [[ "$FILLED" =~ ^[0-9]+$ ]]; then FILLED=0; fi
if [ "$FILLED" -gt "$BAR_WIDTH" ]; then FILLED=$BAR_WIDTH; fi
UNFILLED=$((BAR_WIDTH - FILLED))

printf "${BOLD}Pipeline Overview:${NC}\n"
printf "  %-12s ${BOLD}%-10s${NC}   %-12s ${GREEN}%-10s${NC}   %-12s ${RED}%-10s${NC}\n" "Total Tasks:" "$TOTAL_EXPECTED" "Completed:" "$SUCCESS_COUNT" "Failed:" "$FAILED"
printf "  %-12s ${BLUE}%-10s${NC}   %-12s ${YELLOW}%-10s${NC}   %-12s ${BOLD}%s${NC}\n" "Running:" "$SLURM_RUNNING" "Pending:" "$SLURM_PENDING" "Progress:" "$PERCENT%"

# Bar
printf "  ${CYAN}["
for ((i=0; i<FILLED; i++)); do printf "■"; done
for ((i=0; i<UNFILLED; i++)); do printf " "; done
printf "]${NC}\n"
printf "\n"

# 2. Detailed Process Status
echo -e "${BOLD}Detailed Process Status:${NC}"

# Generate Process Order from Log
ORDER_TMP=$(mktemp)
if [ -f "$LOG_FILE" ]; then
    grep "process >" "$LOG_FILE" | sed -E 's/.*process > ([^ ]+).*/\1/' | awk '!seen[$0]++' > "$ORDER_TMP"
fi

# Generate a temporary file for running/pending tasks from Slurm (using captured state)
SLURM_TMP=$(mktemp)
# Parse SLURM_RAW: Remove leading spaces, replace first space with tab, remove nf- prefix, remove hash suffix
grep " nf-" "$SLURM_RAW" | awk '{
    # $1 is State, $2 is Name (nf-Proc_Hash)
    state = $1;
    name = $2;
    sub(/^nf-/, "", name); # Remove nf-
    sub(/_\(.+/, "", name); # Remove hash part _(x/y)
    print state "\t" name;
}' > "$SLURM_TMP"

# Generate a temporary file for expected totals from Log
TOTALS_TMP=$(mktemp)
if [ -f "$LOG_FILE" ]; then
    # Filter for lines containing " of " (to ensure we have counts) and use tab separator for awk
    # Also strip ANSI color codes rigorously to ensure clean name matching (handles [m, [K, etc)
    grep "process >" "$LOG_FILE" | grep " of " | tail -n 50 | sed -r 's/\x1B\[[0-9;]*[mK]//g' | sed -E 's/.*process > ([^ ]+).+of ([0-9]+).*/\1\t\2/' > "$TOTALS_TMP"
fi

# Generate Retry Counts from Log (Deduplicated by Hash)
# Output: ProcessName \t Hash
RETRY_TMP=$(mktemp)
if [ -f "$LOG_FILE" ]; then
    grep "Execution is retried" "$LOG_FILE" | awk '{
        # Extract Hash [xx/yyyyyy]
        if (match($0, /^\[([^]]+)\]/, h)) {
            hash = h[1];
            if (!seen[hash]++) {
                # Extract Process Name
                if (match($0, /Process `([^`]+)`/, m)) {
                    split(m[1], parts, " ");
                    # Output: ProcessType \t FullTaskName
                    print parts[1] "\t" m[1];
                }
            }
        }
    }' > "$RETRY_TMP"
fi

# Use awk to aggregate stats by process name
# We read ORDER_TMP (file 1), SLURM_TMP (file 2), TOTALS_TMP (file 3), RETRY_TMP (file 4), TRACE_FILE (file 5)
awk -F'\t' -v current_time=$(date +%s) '
BEGIN {
    # Define colors for output
    BOLD="\033[1m"
    RED="\033[0;31m"
    GREEN="\033[0;32m"
    YELLOW="\033[0;33m"
    BLUE="\033[0;34m"
    CYAN="\033[0;36m"
    NC="\033[0m"
    
    # Robust Format (Total ~150 chars)
    # Name(35) Prog(16) Tasks(18) F/R(S)(18) Slurm(12) Rate(10) ETA(14) Finish(20)
    # We use %s%-18s%s for the Fail/Rtry column to handle colors without breaking alignment
    fmt = "%-35s %-16s %-18s %s%-18s%s %-12s %-10s %-14s %-20s"
    
    # Print Header
    printf "%s" fmt "%s\n", BOLD, "Process Name", "Progress", "Done/Total", "", "Fail/Rtry(Succ)", "", "Slurm(R/P)", "Rate", "ETA", "Finish", NC
    printf "%s-------------------------------------------------------------------------------------------------------------------------------------------------------%s\n", CYAN, NC

    # Window for rate calculation (e.g., last 1 hour = 3600s)
    window_sec = 3600
    window_start_timestamp = current_time - window_sec
}
function print_col(text, color, width) {
    return text
}
FNR==NR {
    # Processing ORDER_TMP (File 1)
    proc_order[$1] = FNR;
    next;
}
FILENAME==ARGV[2] {
    # Processing SLURM_TMP (File 2)
    state = $1;
    proc = $2;
    if (proc != "") {
        if (state == "PD") pending_counts[proc]++;
        else running_counts[proc]++; # R or CG
        all_procs[proc]=1;
    }
    next;
}
FILENAME==ARGV[3] {
    # Processing TOTALS_TMP (File 3)
    if ($1 != "") {
        expected_total[$1] = $2;
        all_procs[$1]=1;
    }
    next;
}
FILENAME==ARGV[4] {
    # Processing RETRY_TMP (File 4)
    # $1 = ProcessName, $2 = FullTaskName

    if ($1 != "") {
        if (!seen_retry_task[$2]++) {
            retry_counts[$1]++;
        }
    }
    next;
}
{
    # Processing TRACE_FILE (File 5) (skip header)
    if (FNR > 1) {
        split($4, a, " "); 
        proc_name = a[1]; 
        full_name = $4;
        all_procs[proc_name]=1;
        status = $5;
        hash = $2;
        
        # Count ALL tasks (do not dedup by name, as name might not be unique for logical tasks)
        if (status == "COMPLETED") {
            succeeded[proc_name]++;
        }
        else if (status == "CACHED") cached[proc_name]++;
        else if (status == "FAILED") {
            failed_raw[proc_name]++;
            has_failed[full_name] = 1;
        }

        # Track total tasks seen in trace for this process
        trace_found_count[proc_name]++;
        
        if (status == "COMPLETED") {
            is_completed[full_name] = 1;
            
            d = $7;
            gsub(/[-:]/, " ", d);
            sub(/\..*/, "", d); 
            t = mktime(d);
            
            if (t > 0) {
                if (start_time[proc_name] == 0 || t < start_time[proc_name]) {
                    start_time[proc_name] = t;
                }
                if (t >= window_start_timestamp) {
                    recent_completed[proc_name]++;
                    if (recent_start[proc_name] == 0 || t < recent_start[proc_name]) {
                        recent_start[proc_name] = t;
                    }
                }
            }
        }
    }
} 
END {
    # ---------------------------------------------------------
    # Fix: Merge Truncated/Duplicate Process Names (Orphan Adoption)
    # ---------------------------------------------------------
    
    # 1. Identify "Canonical" names (Active in Trace) and "Phantom" names (Log only)
    for (proc in all_procs) {
        if (trace_found_count[proc] > 0) {
            is_canonical[proc] = 1;
        } else if (expected_total[proc] > 0) {
            is_phantom[proc] = 1;
        }
    }

    # 2. Adoption Logic
    for (phant in is_phantom) {
        best_parent = "";
        best_score = 0;
        
        # Prepare cleaned phantom name
        clean_phant = phant;
        # Remove trailing "..." or similar
        sub(/\.\.+$/, "", clean_phant);
        
        for (can in is_canonical) {
            # Only adopt if Canonical has NO Total yet (or purely relying on trace count)
            # This prevents overwriting a correct total with a mismatched one
            if (expected_total[can] == 0) {
                
                # Match Logic:
                # 1. Prefix Match: Phantom is a prefix of Canonical (Log: "ProcA...", Trace: "ProcABC")
                # 2. Substring: Cleaned Phantom is prefix of Canonical
                # 3. First 15 chars match (last resort)
                
                match_val = 0;
                
                if (index(can, clean_phant) == 1) match_val = 2;
                else if (length(clean_phant) > 10 && substr(can, 1, length(clean_phant)) == clean_phant) match_val = 2;
                else if (length(clean_phant) > 10 && substr(can, 1, 10) == substr(clean_phant, 1, 10)) match_val = 1;
                
                if (match_val > best_score) {
                    best_score = match_val;
                    best_parent = can;
                }
            }
        }
        
        if (best_parent != "") {
            expected_total[best_parent] = expected_total[phant];
            if (proc_order[best_parent] == 0 || (proc_order[phant] > 0 && proc_order[phant] < proc_order[best_parent])) {
                proc_order[best_parent] = proc_order[phant];
            }
            delete all_procs[phant];
        } else {
            # If no parent found, but this is clearly a junk phantom (0 done), hide it strictly?
            # Or keep it valid.
        }
    }

    # Calculate Retry Success and Print
    # Iterate over all tasks seen in trace
    for (t in has_failed) {
        split(t, a, " ");
        p = a[1];
        if (is_completed[t]) {
            retry_success[p]++;
        }
    }


    max_eta_sec = 0;

    for (proc in all_procs) {
        # Fallback: If Total is missing, use Trace Count
        # This fixes cases where Merge failed or Log data is missing, ensuring "Done" tasks always have a valid total
        if ((expected_total[proc] == "" || expected_total[proc] == 0) && trace_found_count[proc] > 0) {
            expected_total[proc] = trace_found_count[proc];
        }

        # Total from Log is most reliable
        total = (expected_total[proc] ? expected_total[proc] : "?");
        
        s = (succeeded[proc] ? succeeded[proc] : 0);
        c = (cached[proc] ? cached[proc] : 0);
        done = s + c;
        
        # If done > total (e.g. log outdated), update total
        if (total != "?" && done > total) total = done;
        
        # Retries: From Log (Unique Tasks)
        f_retry = (retry_counts[proc] ? retry_counts[proc] : 0);
        # Retry Success: From Trace analysis
        f_succ = (retry_success[proc] ? retry_success[proc] : 0);
        
        # Fail = Cumulative Unique Failures (Total unique tasks that ever failed)
        unique_failed_count = 0;
        for (t in has_failed) {
            split(t, a, " ");
            if (a[1] == proc) unique_failed_count++;
        }
        
        r = (running_counts[proc] ? running_counts[proc] : 0);
        p = (pending_counts[proc] ? pending_counts[proc] : 0);
        
        done_tot_str = done "/" total;
        
        # Format: Fail/Rtry(Succ)
        # Fail = Cumulative Unique Failures (Total unique tasks that ever failed)
        # Rtry = Cumulative Unique Retried Tasks (Total unique tasks that were retried)
        # Succ = Unique tasks that failed but eventually succeeded
        
        fail_rtry_str = sprintf("%d/%d(%d)", unique_failed_count, f_retry, f_succ);
        
        # Color logic:
        # Red if there are failures that have not succeeded (approximate check)
        # Yellow if there are retries but all seem to have succeeded
        
        c_start = "";
        c_end = "";
        if (unique_failed_count > f_succ) { c_start = RED; c_end = NC; }
        else if (f_retry > 0) { c_start = YELLOW; c_end = NC; }
        
        # Compact Progress Bar
        pct = 0;
        if (total != "?" && total > 0) {
            pct = (done / total) * 100;
        }
        bar_len = 5;
        filled = int((pct / 100) * bar_len);
        bar = "[";
        for (i=1; i<=filled; i++) bar = bar "=";
        for (i=filled+1; i<=bar_len; i++) bar = bar ".";
        bar = bar "]";
        
        progress_str = sprintf("%s %3.0f%%", bar, pct);
        
        slurm_str = sprintf("%d/%d", r, p);
        
        rem = "?";
        if (total != "?") {
            if (done > total) total = done; 
            rem = total - done;
        }
        
        rate_str = "-";
        eta_str = "-";
        finish_str = "-";
        
        use_rate = 0;
        if (r > 0) {
            if (recent_completed[proc] > 5) { 
                elapsed = current_time - recent_start[proc];
                if (elapsed < 60) elapsed = 60; 
                use_rate = (recent_completed[proc] / elapsed) * 60;
            } else if (s > 0 && start_time[proc] > 0) {
                 elapsed = current_time - start_time[proc];
                 if (elapsed > 0) {
                    use_rate = (s / elapsed) * 60;
                 }
            }
        }
        
        if (rem == 0) {
            eta_str = "Done";
        } else if (use_rate > 0) {
            rate_str = sprintf("%.1f", use_rate);
            
            if (rem != "?" && rem > 0) {
                eta_sec = (rem / use_rate) * 60;
                if (eta_sec > max_eta_sec) max_eta_sec = eta_sec;
                
                d = int(eta_sec / 86400);
                rem_sec = eta_sec % 86400;
                h = int(rem_sec / 3600);
                rem_sec = rem_sec % 3600;
                m = int(rem_sec / 60);
                s = int(rem_sec % 60);
                
                if (d > 0) eta_str = sprintf("%dd%02dh", d, h);
                else if (h > 0) eta_str = sprintf("%dh%02dm", h, m);
                else eta_str = sprintf("%dm%02ds", m, s);
                
                finish_time = current_time + eta_sec;
                finish_str = strftime("%Y-%m-%d %H:%M:%S", finish_time);
            }
        }
        
        ord = (proc_order[proc] ? proc_order[proc] : 999);
        
        # Truncate Name for display
        disp_name = proc;
        if (length(disp_name) > 34) disp_name = substr(disp_name, 1, 33) "…";

        printf "%d\t", ord
        printf fmt "\n", disp_name, progress_str, done_tot_str, c_start, fail_rtry_str, c_end, slurm_str, rate_str, eta_str, finish_str
    }
    
    if (max_eta_sec > 0) {
        finish_time = current_time + max_eta_sec;
        finish_str = strftime("%Y-%m-%d %H:%M:%S", finish_time);
        printf "9999\t%s-------------------------------------------------------------------------------------------------------------------------------------------------------%s\n", CYAN, NC
        printf "9999\t%s" fmt "%s\n", BOLD, "Pipeline Estimate", "-", "-", "", "-", "", "-", "-", "Max Finish:", finish_str, NC
    }
}' "$ORDER_TMP" "$SLURM_TMP" "$TOTALS_TMP" "$RETRY_TMP" "$TRACE_FILE" | sort -n | cut -f2-

if [ -n "$SLURM_TMP" ] && [ -f "$SLURM_TMP" ]; then rm "$SLURM_TMP"; fi
if [ -n "$TOTALS_TMP" ] && [ -f "$TOTALS_TMP" ]; then rm "$TOTALS_TMP"; fi
if [ -n "$ORDER_TMP" ] && [ -f "$ORDER_TMP" ]; then rm "$ORDER_TMP"; fi
if [ -n "$RETRY_TMP" ] && [ -f "$RETRY_TMP" ]; then rm "$RETRY_TMP"; fi
echo ""

# 3. Retried Tasks (Triggered Resubmission - Active/Failed Only)
if [ -f "$LOG_FILE" ]; then
    # Filter out tasks that have eventually succeeded
    awk -v trace_file="$TRACE_FILE" -v log_file="$LOG_FILE" -v bold="${BOLD}" -v nc="${NC}" -v cyan="${CYAN}" -v yellow="${YELLOW}" '
    BEGIN {
        # 1. Load Completed Tasks from Trace
        while ((getline < trace_file) > 0) {
            split($0, f, "\t");
            name = f[4];
            status = f[5];
            if (status == "COMPLETED") {
                completed[name] = 1;
            }
        }
        close(trace_file);

        # 2. Process Log for Retries
        # Use awk to deduplicate lines (Nextflow log can contain duplicate retry messages)
        cmd = "grep \"Execution is retried\" \"" log_file "\" | awk \"!seen[\\$0]++\" | tail -n 10";
        count = 0;
        while ((cmd | getline) > 0) {
            if (match($0, /Process `([^`]+)` terminated with an error exit status \(([0-9]+)\) -- Execution is retried \(([0-9]+)\)/, m)) {
                name = m[1];
                exit_code = m[2];
                retry_num = m[3];
                
                if (!completed[name]) {
                    if (count == 0) {
                        print yellow bold "Retried Tasks (Active/Failed - Last 10):" nc;
                        # Width: 80 + 1 + 12 + 1 + 10 = 104
                        sep = ""; for(i=1;i<=104;i++) sep = sep "-";
                        print cyan sep nc;
                        printf "%s%-80s %-12s %-10s%s\n", bold, "Task Name", "Exit Code", "Retry #", nc;
                        print cyan sep nc;
                    }
                    printf "%-80s %-12s %-10s\n", substr(name, 1, 80), exit_code, retry_num;
                    count++;
                }
            }
        }
        close(cmd);
        
        if (count > 0) {
            print cyan sep nc;
            print "";
        }
    }
    '
fi

# 4. Recent Failures
if [ "$FAILED" -gt 0 ]; then
    echo -e "${RED}${BOLD}Recent Failures (Last 5):${NC}"
    # Width: 80 + 1 + 12 + 1 + 12 + 1 + 30 = 137
    SEP="-----------------------------------------------------------------------------------------------------------------------------------------"
    echo -e "${CYAN}${SEP}${NC}"
    printf "${BOLD}%-80s %-12s %-12s %-30s${NC}\n" "Task Name" "Exit Code" "Duration" "Work Dir"
    echo -e "${CYAN}${SEP}${NC}"
    grep "FAILED" "$TRACE_FILE" | tail -n 5 | awk -F'\t' '{printf "%-80s %-12s %-12s %-30s\n", substr($4, 1, 80), $6, $8, $2}'
    echo -e "${CYAN}${SEP}${NC}"
    echo ""
fi

# 5. Resource Usage (Last 5 Completed)
echo -e "${BOLD}Resource Usage (Last 5 Completed Tasks):${NC}"
grep "COMPLETED" "$TRACE_FILE" | tail -n 5 | awk -F'\t' -v bold="${BOLD}" -v nc="${NC}" -v cyan="${CYAN}" '
BEGIN { max_len = 15; }
{
    names[NR] = $4;
    durations[NR] = $8;
    cpus[NR] = $10;
    rss[NR] = $11;
    vmem[NR] = $12;
    io[NR] = $13 " / " $14;
    if (length($4) > max_len) max_len = length($4);
}
END {
    if (max_len > 80) max_len = 80;
    # Name(max) Dur(12) CPU(10) RSS(12) VMEM(12) IO(20)
    fmt = "%-" max_len "s %-12s %-10s %-12s %-12s %-20s\n";
    
    # Dashed line
    # Width = max_len + 1 + 12 + 1 + 10 + 1 + 12 + 1 + 12 + 1 + 20 = max_len + 71
    width = max_len + 71;
    line = ""; for(i=1; i<=width; i++) line = line "-";
    
    printf "%s%s%s\n", cyan, line, nc;
    printf bold fmt nc, "Task Name", "Duration", "%CPU", "Peak RSS", "Peak VMEM", "I/O (R/W)";
    printf "%s%s%s\n", cyan, line, nc;
    
    for (i=1; i<=NR; i++) {
        disp_name = names[i];
        if (length(disp_name) > max_len) disp_name = substr(disp_name, 1, max_len-1) "…";
        printf fmt, disp_name, durations[i], cpus[i], rss[i], vmem[i], io[i];
    }
    if (NR > 0) printf "%s%s%s\n", cyan, line, nc;
}'
echo ""

# 5. Log Tail
if [ "$SHOW_LOG" = true ] && [ -f "$LOG_FILE" ]; then
    echo -e "${BOLD}Latest Log Messages:${NC}"
    SEP="----------------------------------------------------------------------------------------------------------------------------------------------------------------"
    echo -e "${CYAN}${SEP}${NC}"
    # Extract the last block starting with "executor >" but filter for process lines
    tail -n 100 "$LOG_FILE" | awk '/executor >/{buf=$0; next} {buf=buf ORS $0} END{print buf}' | grep -E "executor >|process >" | fold -w 160
    echo -e "${CYAN}${SEP}${NC}"
fi

echo -e "${BOLD}${CYAN}================================================================================================================================================================${NC}"
